### PR TITLE
add .NET checker

### PR DESCRIPTION
**Pull request by JesterOrNot**

### CODE REVIEW

**Comment by svenefftinge** [comment]
It also removes the make / cmake part. Why is that?

**Comment by JesterOrNot** [comment]
So sorry I'll fix that 😅 
@svenefftinge

**Comment by JesterOrNot** [comment]
@svenefftinge better?

**Comment by svenefftinge** [comment]
Yes, thanks :-)
Could you clean up the superfluous newlines and also add a test case?

**Comment by JesterOrNot** [comment]
@svenefftinge what newlines?

**Comment by JesterOrNot** [comment]
Sven where do tests go?

**Comment by svenefftinge** [comment]
https://github.com/gitpod-io/gitpod-yml-inferrer/blob/master/src/config-inferrer.spec.ts#L32

**Comment by jankeromnes** [comment]
Heyo! I took the liberty to rebase and squash the commits here, because they seem useful.

Also, I've removed the unrelated `stack.yml` contribution:

```js
    protected async checkStack(ctx: Context) {
        if (await ctx.exists("stack.yml") || await ctx.exists("stack.yaml")) {
            this.addCommand(ctx.config, "stack install", "init");
        }
    }
```

If you care about it, please open another Pull Request for it. However, please note the presence of a `stack.yml` file can mean many different things:
- https://gist.github.com/garystafford/9b0b596e1ae82d7a073fbf96b571defb
- https://docs.openfaas.com/openfaas-cloud/self-hosted/troubleshoot/#stackyml-not-found
- https://github.com/hms-dbmi/stack/blob/master/stack.yml
- etc.

**Pull request merged**
